"use client";

import { useState } from "react";
import { X } from "lucide-react";

export type FieldType = "text" | "number" | "date" | "select" | "textarea" | "checkbox";

export interface FieldOption {
  value: string;
  label: string;
}

export interface FieldConfig {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: FieldOption[];
  placeholder?: string;
}

interface Props {
  title: string;
  fields: FieldConfig[];
  initialValues?: Record<string, any>;
  onSubmit: (values: Record<string, any>) => Promise<{ error: string | null }>;
  onClose: () => void;
}

// One form renders every "Add new ..." screen in this dashboard —
// Subjects, Stages, Exam Types, Class Sections, Students all reuse
// this instead of a bespoke modal each. Primary keys are UUIDs
// generated by the database, so unlike Buspulse's version of this
// component, there's no ID field or ID-suggestion logic here at all.
export default function AddEntityModal({ title, fields, initialValues, onSubmit, onClose }: Props) {
  const [values, setValues] = useState<Record<string, any>>(initialValues ?? {});
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function setField(key: string, value: any) {
    setValues((v) => ({ ...v, [key]: value }));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const missing = fields.find((f) => f.required && !values[f.key] && values[f.key] !== 0);
    if (missing) {
      setError(`الحقل "${missing.label}" مطلوب`);
      return;
    }
    setSubmitting(true);
    setError(null);
    const { error: submitError } = await onSubmit(values);
    setSubmitting(false);
    if (submitError) setError(submitError);
    else onClose();
  }

  return (
    <div
      onClick={onClose}
      className="fade-in"
      style={{
        position: "fixed", inset: 0, background: "rgba(44,52,84,0.55)",
        display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 16,
      }}
    >
      <form
        onClick={(e) => e.stopPropagation()}
        onSubmit={handleSubmit}
        className="card"
        style={{ padding: "1.75rem", width: 480, maxWidth: "100%", maxHeight: "85vh", overflowY: "auto" }}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}>
          <h2 style={{ margin: 0, fontSize: "1.15rem", color: "var(--indigo)" }}>{title}</h2>
          <button type="button" onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--steel)" }}>
            <X size={20} />
          </button>
        </div>

        {fields.map((f) => (
          <div key={f.key} style={{ marginBottom: 16 }}>
            <label style={{ display: "block", fontSize: "0.85rem", fontWeight: 600, color: "var(--steel)", marginBottom: 5 }}>
              {f.label}
              {f.required && <span style={{ color: "var(--red)" }}> *</span>}
            </label>

            {f.type === "select" ? (
              <select value={values[f.key] ?? ""} onChange={(e) => setField(f.key, e.target.value)} className="input">
                <option value="">— اختر —</option>
                {(f.options ?? []).map((opt) => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            ) : f.type === "textarea" ? (
              <textarea value={values[f.key] ?? ""} placeholder={f.placeholder}
                onChange={(e) => setField(f.key, e.target.value)} className="input" style={{ height: 80, resize: "vertical" }} />
            ) : f.type === "checkbox" ? (
              <input type="checkbox" checked={!!values[f.key]} onChange={(e) => setField(f.key, e.target.checked)} />
            ) : (
              <input
                type={f.type}
                value={values[f.key] ?? ""}
                placeholder={f.placeholder}
                onChange={(e) => setField(f.key, f.type === "number" ? e.target.valueAsNumber : e.target.value)}
                className="input"
              />
            )}
          </div>
        ))}

        {error && <p style={{ color: "var(--red)", fontSize: "0.85rem", marginBottom: 12 }}>{error}</p>}

        <div style={{ display: "flex", gap: 10, marginTop: 8 }}>
          <button type="submit" disabled={submitting} className="btn btn-gold" style={{ flex: 1 }}>
            {submitting ? "جارٍ الحفظ..." : "حفظ"}
          </button>
          <button type="button" onClick={onClose} className="btn btn-secondary">إلغاء</button>
        </div>
      </form>
    </div>
  );
}
